project:
  type: website
  output-dir: docs

website:
  title: "GSOC 2025 - Pitch Correction for Sound Playback in Sequencer Blog"
  navbar:
    search: true
    # left:
    #   - text: "Home"
    #     href: index.qmd
  # navbar:
    # right:
      # - about.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    code-fold: true
jupyter: python3



