---
title: "Introduction"
author: "TheKaceFiles"
date: "2025-05-23"
categories: [personal]
---

Hi! I'm the TheKaceFiles and I'm currently one of the GSOC contributors for Blender! This summer, I'll be implementing a pitch correction toggle for **Blender's Video Sequence Editor (VSE)** under Aras Pranckevičius. This blog will be primarily used for notes covering Blender's codebase, the pitch correction research papers, review concepts from digital signal processing, whatever topics I find interesting, or just my thinking process. Do note that my thoughts/notes will not be always be organized or precise, but they will be reorganized once I have a better grasp.


I will admit, I do feel both nervous and excited for this project. Nervous, as in, I'm worried that I will be unable to complete the project within the upcoming months and that this is one of the biggest project/feature I will be undertaking. Excited, as in, I will be learning (and relearning) many new things like concepts for pitch correction and navigating Blender's codebase. Over the next few days/weeks, I will reviewing and [Digital Signals Theory](https://brianmcfee.net/dstbook-site/content/ch01-signals/Preliminaries.html) by Brian McFee and [A Digital Signal Processing Primer](Kenneth Steiglitz) by Kenneth Steiglitz and putting up my own notes up. One of the biggest gripes I have about these books is that they never have enough examples or solutions (which is understandable as they're trying to minimize the page count for printing!) My notes are meant to bridge this gap and meant to help me (and hopefully others) better understand the material! 


We'll see how that goes until then!
